### ISSUE TITLE
请问在分库分表时，分片键不是纯数字形式的，但是有不想写侵入性的java代码，如何能做到？

### ISSUE THREAD

**Issue by TongHaoException** [shardingjdbc/sharding-jdbc#445]
请问在分库分表时，分片键不是纯数字形式的，但是有不想写侵入性的java代码，如何能做到。也就是说只需要配置yaml文件来实现分库分表。由于业务的需要，想通过具有业务性的字段来分库分表，但是这些业务性的字段又不是纯数字的。

**Comment by cocodroid** [comment]
可以用hashcode来呀(^_^)  /偷笑

**Comment by terrymanu** [comment]
分片策略是应用开发方自己写的，代码很灵活，如何分片都可以

**Comment by TongHaoException** [comment]
为何采用algorithmExpression: t_transaction_${order_line_item.hashCode() % 5}这种形式，每次hashCode出来的值都不一样？

**Comment by cocodroid** [comment]
@TongHaoException java的hashcode哦，应该是一样的

**Comment by TongHaoException** [comment]
也就是说还是要写java代码的咯？

发件人: verysu [mailto:notifications@github.com]
发送时间: 2017年11月16日 20:28
收件人: shardingjdbc/sharding-jdbc <sharding-jdbc@noreply.github.com>
抄送: Tong, Hao, Connext China <hao.tong@connext.com.cn>; Mention <mention@noreply.github.com>
主题: Re: [shardingjdbc/sharding-jdbc] 请问在分库分表时，分片键不是纯数字形式的，但是有不想写侵入性的java代码，如何能做到？ (#445)


@TongHaoException<https://github.com/tonghaoexception> java的hashcode哦，应该是一样的

**Comment by changjiasheng** [comment]
For example : table_name = user and you want split by login_name,and login_name is String type.
You can use like this.
sharding.jdbc.config.sharding.tables.user.databaseStrategy.inline.algorithm-inline-expression=ds_${Math.abs(login_name.hashCode() % 3) }

I add Math.abs() to avoid appear negative number，because java hashCode may be negative number.
